@base = http://localhost:3000
@remote = https://team-bountiful.onrender.com


//***********************
// USERS routes (LOCAL) *
//***********************

### list users in DB
get {{base}}/users

### insert new user to DB
post {{base}}/users/createNewUser HTTP/1.1 
content-type: application/json

{
    "firstName": "Eric",
    "lastName": "Shewchuk",
    "email": "she12041@byui.edu",
    "userName": "eShew823",
    "password": "Eric823!",
    "accessLevel": "user",
    "accountModified": ""
}

### update user in DB
put {{base}}/users/updateUser/**id** HTTP/1.1 
content-type: application/json

{
    "firstName": "Eric",
    "lastName": "Shewchuk",
    "email": "she12041@byui.edu",
    "userName": "eShew823",
    "password": "Eric823!",
    "accessLevel": "admin",
    "accountModified": ""
}

### change password for user in DB
patch {{base}}/users/changePassword/**id** HTTP/1.1 
content-type: application/json

{
    "password": "NewPass823!"
}

### set access level for user in DB
patch {{base}}/users/setAccessLevel/**id** HTTP/1.1
content-type: application/json

{
    "accessLevel": "admin"
}

### delete user in DB
delete {{base}}/users/removeUser/**id** HTTP/1.1

//****************************
// CHARACTERS routes (LOCAL) *
//****************************

### list all characters in DB
get {{base}}/characters

### list single character in DB
get {{base}}/characters/**id**

### list characters by book in DB
get {{base}}/characters/**bookId**

### list characters by quality in DB
get {{base}}/characters/**quality**

### insert new character to DB
post {{base}}/characters/createNewCharacter HTTP/1.1
content-type: application/json

{
    "characterName": "Nephi",
    "firstBookSeen": "1Nephi",
    "firstVerseSeen": "1:1",
    "quality": "Hero",
    "notes": "Son of Lehi. Righteous and knows his father to be a true prophet. Repeatedly calls upon the Lord for wisdom and knowledge. Builds the boat that brings his family to the new lands. During the time in the wilderness, he marries and has children. The name of his wife, the name and number of his children, is never given."
}

### update character in DB
put {{base}}/characters/updateCharacter/**id** HTTP/1.1
content-type: application/json

{
    "characterName": "Nephi",
    "firstBookSeen": "1Nephi",
    "firstVerseSeen": "1:1",
    "quality": "Hero",
    "notes": "Son of Lehi. Righteous and knows his father to be a true prophet. Repeatedly calls upon the Lord for wisdom and knowledge. Builds the boat that brings his family to the new lands. During the time in the wilderness, he marries and has children. The name of his wife, the name and number of his children, is never given."
}
