@base = http://localhost:3000
@remote = https://team-bountiful.onrender.com


//***********************
// USERS routes (LOCAL) *
//***********************

### list users in DB
get {{base}}/users

### insert new user to DB
post {{base}}/users/createNewUser HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "userName": "",
    "password": "",
    "accessLevel": "user",
    "accountModified": ""
}

### update user in DB
put {{base}}/users/updateUser/**id** HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "userName": "",
    "password": "",
    "accessLevel": "admin",
    "accountModified": ""
}

### change password for user in DB
patch {{base}}/users/changePassword/**id** HTTP/1.1
content-type: application/json

{
    "password": ""
}

### set access level for user in DB
patch {{base}}/users/setAccessLevel/**id** HTTP/1.1
content-type: application/json

{
    "accessLevel": "admin"
}

### delete user in DB
delete {{base}}/users/removeUser/**id** HTTP/1.1


//****************************
// CHARACTERS routes (LOCAL) *
//****************************

### list all characters in DB
get {{base}}/characters

### list details of single character in DB
get {{base}}/characters/**id**

### list characters by book in DB
get {{base}}/characters/listByBook/**book**

### list characters by quality in DB
get {{base}}/characters/listByQuality/**quality**

### insert new character to DB
post {{base}}/characters/createNewCharacter HTTP/1.1
content-type: application/json

{
    "characterName": "Himni",
    "firstBookSeen": "Mosiah",
    "firstVerseSeen": "27:8",
    "quality": "Hero",
    "notes": "Son of Mosiah who was persecuting members of the church with Alma. Becomes converted and later teaches gospel to Lamanites in the lands of Lamoni and his father."
}

### update character in DB
put {{base}}/characters/updateCharacter/**id** HTTP/1.1
content-type: application/json

{
    "characterName": "",
    "firstBookSeen": "",
    "firstVerseSeen": "",
    "quality": "",
    "notes": ""
}


//************************
// QUOTES routes (LOCAL) *
//************************

### list all quotes in DB
get {{base}}/quotes

### list all quotes by book
get {{base}}/quotes/**bookName**

### list all quotes by character
get {{base}}/quotes/**characterId**

### insert new quote to DB
post {{base}}/quotes/createNewQuote HTTP/1.1
content-type: application/json

{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookName": "1 Nephi",
    "verse": "3:7",
    "characterQuality": "Hero",
    "text": "I will go and do the things which the Lord hath commanded."
}

### update quote in DB
put {{base}}/quotes/updateQuote/**id** HTTP/1.1
content-type: application/json

{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookName": "1 Nephi",
    "verse": "3:7",
    "characterQuality": "Hero",
    "text": "I will go and do the things which the Lord hath commanded."
}


//************************
// IMAGES routes (LOCAL) *
//************************

### list all images in DB
get {{base}}/images

### list all images by book
get {{base}}/images/imageByBook/**bookName**

### list all images by character
get {{base}}/images/**characterId** 

### insert new image to DB
post {{base}}/images/createNewImage HTTP/1.1
content-type: application/json

{
    "characterId": "692b5d1e2c191fddead2f44d",
    "characterName": "Angel of the Lord",
    "bookWhereSeen": "1 Nephi",
    "characterQuality": "Hero",
    "filename": "angel_of_the_lord.jpeg",
    "caption": "Angel appears to Nephi",
    "description": "An image of the Angel of the Lord descending to rebuke Laman and Lemuel. Image from the Book of Mormon Videos and Images collection on churchofjesuschrist.org",
    "source": "https://www.churchofjesuschrist.org/media/collection/1-nephi-3-5-images?lang=eng"
}

### update image in DB
put {{base}}/images/updateImage/692b81e520a7b1e303849e25 HTTP/1.1
content-type: application/json

{
    "characterId": "692b5d1e2c191fddead2f44d",
    "characterName": "Angel of the Lord",
    "bookWhereSeen": "1 Nephi",
    "characterQuality": "Hero",
    "filename": "angel_of_the_lord.jpeg",
    "caption": "Angel appears to Nephi",
    "description": "An image of the Angel of the Lord descending to rebuke Laman and Lemuel. Image from the Book of Mormon Videos and Images collection on churchofjesuschrist.org",
    "source": "https://www.churchofjesuschrist.org/media/collection/1-nephi-3-5-images?lang=eng"
}

### delete image in DB
delete {{base}}/images/removeImage/**image-id** HTTP/1.1


//************************
// USERS routes (RENDER) *
//************************

### list users in DB
get {{remote}}/users

### insert new user to DB
post {{remote}}/users/createNewUser HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "userName": "",
    "password": "",
    "accessLevel": "user",
    "accountModified": ""
}

### update user in DB
put {{remote}}/users/updateUser/**id** HTTP/1.1
content-type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "",
    "userName": "",
    "password": "",
    "accessLevel": "user",
    "accountModified": ""
}

### change password for user in DB
patch {{remote}}/users/changePassword/**id** HTTP/1.1
content-type: application/json

{
    "password": "NewPass823!"
}

### set access level for user in DB
patch {{remote}}/users/setAccessLevel/**id** HTTP/1.1
content-type: application/json

{
    "accessLevel": "admin"
}

### delete user in DB
delete {{remote}}/users/removeUser/**id** HTTP/1.1


//*****************************
// CHARACTERS routes (RENDER) *
//*****************************

### list all characters in DB
get {{remote}}/characters

### list details of single character in DB
get {{remote}}/characters/**id**

### list characters by book in DB
get {{remote}}/characters/**bookId**

### list characters by quality in DB
get {{remote}}/characters/**quality**

### insert new character to DB
post {{remote}}/characters/createNewCharacter HTTP/1.1
content-type: application/json

{
    "characterName": "Nephi",
    "firstBookSeen": "1 Nephi",
    "firstVerseSeen": "1:1",
    "quality": "Hero",
    "notes": "Son of Lehi. Righteous and knows his father to be a true prophet. Repeatedly calls upon the Lord for wisdom and knowledge. Builds the boat that brings his family to the new lands. During the time in the wilderness, he marries and has children. The name of his wife, the name and number of his children, is never given."
}

### update character in DB
put {{remote}}/characters/updateCharacter/**id** HTTP/1.1
content-type: application/json

{
    "characterName": "Nephi",
    "firstBookSeen": "1 Nephi",
    "firstVerseSeen": "1:1",
    "quality": "Hero",
    "notes": "Son of Lehi. Righteous and knows his father to be a true prophet. Repeatedly calls upon the Lord for wisdom and knowledge. Builds the boat that brings his family to the new lands. During the time in the wilderness, he marries and has children. The name of his wife, the name and number of his children, is never given."
}


//*************************
// QUOTES routes (RENDER) *
//*************************

### list all quotes in DB
get {{remote}}/quotes

### list all quotes by book
get {{remote}}/quotes/**bookId**

### list all quotes by character
get {{remote}}/quotes/**characterId**

### insert new quote to DB
post {{remote}}/quotes/createNewQuote HTTP/1.1
content-type: application/json

{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookName": "1 Nephi",
    "verse": "3:7",    
    // "whereFound": "1 Nephi 3:7",
    "characterQuality": "Hero",
    "text": "I will go and do the things which the Lord hath commanded."
}

### update quote in DB
put {{remote}}/quotes/updateQuote/**id** HTTP/1.1
content-type: application/json

{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookName": "1 Nephi",
    "verse": "3:7",    
    // "whereFound": "1 Nephi 3:7",
    "characterQuality": "Hero",
    "text": "I will go and do the things which the Lord hath commanded."
}


//*************************
// IMAGES routes (RENDER) *
//*************************

### list all images in DB
get {{remote}}/images

### list all images by book
get {{remote}}/images/**bookId**

### list all images by character
get {{remote}}/images/**characterId** 

### insert new image to DB
post {{remote}}/images/createNewImage HTTP/1.1
content-type: application/json

{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookWhereSeen": "1 Nephi",
    "characterQuality": "Hero",
    "filename": "nephi_donkey.jpeg",
    "caption": "Nephi with a donkey",
    "description": "An image of Nephi with a donkey. Image from the Book of Mormon Videos and Images collection on churchofjesuschrist.org",
    "source": "https://www.churchofjesuschrist.org/media/collection/1-nephi-1-2-images?lang=eng"
}

### update image in DB
put {{remote}}/images/updateImage/**id** HTTP/1.1
content-type: application/json
{
    "characterId": "**id**",
    "characterName": "Nephi",
    "bookWhereSeen": "1 Nephi",
    "characterQuality": "Hero",
    "filename": "nephi_donkey.jpeg",
    "caption": "Nephi with a donkey",
    "description": "An image of Nephi with a donkey. Image from the Book of Mormon Videos and Images collection on churchofjesuschrist.org",
    "source": "https://www.churchofjesuschrist.org/media/collection/1-nephi-1-2-images?lang=eng"
}

### delete image in DB
delete {{remote}}/images/removeImage/**id** HTTP/1.1